# Generated by Django 5.1.4 on 2024-12-26 09:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credit',
            name='payment_confirmation_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 26, 18, 12, 8, 53125)),
        ),
        migrations.AddField(
            model_name='credit',
            name='payment_due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 18, 12, 8, 53125)),
        ),
        migrations.AlterField(
            model_name='credit',
            name='withdrawal_account',
            field=models.ForeignKey(limit_choices_to={'category.is_credit': True}, on_delete=django.db.models.deletion.PROTECT, to='budgeting.assetcategory'),
        ),
    ]
