# Generated by Django 5.1.4 on 2024-12-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_asset_amount_assetcategory_is_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='payment_confirmation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='payment_due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
