# Generated by Django 5.1.4 on 2024-12-26 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_alter_credit_payment_confirmation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcategory',
            name='is_credit',
        ),
        migrations.AddField(
            model_name='asset',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='payment_confirmation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='payment_due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='withdrawal_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.asset'),
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
