# Generated by Django 5.1.4 on 2024-12-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_cashflow_cashflowcategory_delete_expence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='memo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
