# Generated by Django 5.1.4 on 2025-01-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_alter_cashflow_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_credit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='payment_confirmation_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='withdrawal_account',
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_date', models.DateTimeField(null=True)),
                ('payment_confirmation_date', models.DateField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.asset')),
                ('withdrawal_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.credit')),
            ],
        ),
    ]
