# Generated by Django 5.1.4 on 2025-01-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0007_remove_asset_is_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='budgeting.asset'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='withdrawal_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_account', to='budgeting.asset'),
        ),
    ]
