# Generated by Django 5.1.4 on 2025-01-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0008_alter_credit_asset_alter_credit_withdrawal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='withdrawal_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_account', to='budgeting.asset'),
        ),
    ]
