# Generated by Django 5.1.4 on 2025-01-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0009_alter_credit_withdrawal_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='payment_confirmation_date',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='payment_due_date',
        ),
        migrations.AddField(
            model_name='credit',
            name='payment_confirmation_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='payment_due_day',
            field=models.IntegerField(null=True),
        ),
    ]
