# Generated by Django 5.1.4 on 2025-01-16 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0010_remove_credit_payment_confirmation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='payment_confirmation_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='payment_due_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='withdrawal_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.asset'),
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
