# Generated by Django 5.1.4 on 2025-02-11 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0011_asset_payment_confirmation_day_asset_payment_due_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='confirmed_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowcategory',
            name='sub_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='payment_confirmation_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='payment_due_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='withdrawal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.asset'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
