# Generated by Django 5.1.4 on 2025-02-11 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0012_asset_confirmed_payment_cashflowcategory_sub_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowcategory',
            name='sub_name',
        ),
        migrations.CreateModel(
            name='CashflowSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_income', models.BooleanField(default=False)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.cashflowcategory')),
            ],
        ),
    ]
