# Generated by Django 5.1.4 on 2025-02-11 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0013_remove_cashflowcategory_sub_name_cashflowsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.cashflowsubcategory'),
        ),
    ]
