# Generated by Django 5.1.4 on 2025-02-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0014_alter_cashflow_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowsubcategory',
            name='is_income',
        ),
    ]
