# Generated by Django 5.1.4 on 2025-02-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0015_remove_cashflowsubcategory_is_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='payment_confirmation_day',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='payment_due_day',
        ),
    ]
