# Generated by Django 5.1.4 on 2025-02-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0016_remove_asset_payment_confirmation_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='confirmed_payment',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
